#!/bin/bash

set -e

echo ">>>>>> Starting E2E >>>>>>>>"

NAME=lib-appsec-kafka_kafka_1

docker-compose down --remove-orphans && docker-compose up -d
until [ $(docker inspect -f {{.State.Running}} $NAME) ]; do
	echo "waiting for kafka..."
	sleep 0.1;
done;

sbt clean it:test

docker-compose down

echo ">>>>>> Finished E2E >>>>>>>>"
