addSbtPlugin("org.scalastyle"            %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"          % "1.6.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"           % "2.4.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"           % "0.1.13")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"               % "2.2.12")
addSbtPlugin("com.47deg"                 % "sbt-microsites"         % "1.2.1")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"           % "3.9.4")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"                % "2.0.1")
