addSbtPlugin("org.scalastyle"           %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"         % "1.8.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"          % "2.4.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"          % "0.1.18")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"              % "2.2.21")
addSbtPlugin("com.47deg"                 % "sbt-microsites"        % "1.3.3")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"          % "3.9.7")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"               % "2.1.1")
